spring:
  # devtools
  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
      database-platform: org.hibernate.dialect.H2Dialect