spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/market
    username: admin
    password: 0000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect